# Test against this version of Node.js
environment:
  nodejs_version: "0.10"

# Install scripts. (runs after repo cloning)
install:
  - echo 'Cloning Lib_UNO library using tm-build account'
  - git clone https://tm-build:$git_pwd@github.com/TMContent/Lib_UNO.git
#  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
 # - node --version
 # - npm --version
  # run tests
 # - npm test

# Don't actually build.
build: off